spring:
  datasource:
    username: # db's username
    password: # db's password
    url: # db's connection endpoint

  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
      
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/eazybankdev/protocol/openid-connect/certs
